### ISSUE TITLE
Execution time - is it a problem?

### ISSUE THREAD

**Issue by Dronakurl** [Dlurak/muxbar#2]
Great project!
I noticed that with the default config, the execution of muxbar takes about 250ms, with only time, it takes only 8ms.
I wondered, if that's a problem, i.e. that muxbar takes significant system resources.
Or is it just IO that doesn't stall anything

**Comment by Dlurak** [comment]
Thanks for feedback.
The problem lies in the cpu module, to measure cpu usage muxbar uses the [`sysinfo`](https://crates.io/crates/sysinfo) crate. It is cross plattform and generally pretty good, but it needs to wait for a short time to measure cpu usage. 

---

It isn't totally bad, at least all modules are run in parallel, so only the slowest module counts and even multiple cpu modules don't add up but you're still right, it is quite slow!

---

I have a quite complex and big idea how to fix it, but it would include breaking changes to the config.

**Comment by Dronakurl** [comment]
Wow, that was quick! Since this waiting doesn't take resources, it should be totally fine, I tink.  
Another thing: I wondered, whether it would be better to have each module in a separate file containing everything that is needed. This way, it would be more extensible. Right now, you have to change things in several places to add a module.
I'm new to Rust, so I wondered, whether it is the right way to do it.
